export const FETCH_DASHBOARD_DATA_REQUEST = 'FETCH_DASHBOARD_DATA_REQUEST';
export const FETCH_DASHBOARD_DATA_SUCCESS = 'FETCH_DASHBOARD_DATA_SUCCESS';
export const FETCH_DASHBOARD_DATA_FAILURE = 'FETCH_DASHBOARD_DATA_FAILURE';

export const FETCH_PROJECT_STATS_REQUEST = 'FETCH_PROJECT_STATS_REQUEST';
export const FETCH_PROJECT_STATS_SUCCESS = 'FETCH_PROJECT_STATS_SUCCESS';
export const FETCH_PROJECT_STATS_FAILURE = 'FETCH_PROJECT_STATS_FAILURE';

export const FETCH_PROJECT_CATEGORY_CHART_REQUEST = 'FETCH_PROJECT_CATEGORY_CHART_REQUEST';
export const FETCH_PROJECT_CATEGORY_CHART_SUCCESS = 'FETCH_PROJECT_CATEGORY_CHART_SUCCESS';
export const FETCH_PROJECT_CATEGORY_CHART_FAILURE = 'FETCH_PROJECT_CATEGORY_CHART_FAILURE';

export const FETCH_PROJECT_STATUS_CHART_REQUEST = 'FETCH_PROJECT_STATUS_CHART_REQUEST';
export const FETCH_PROJECT_STATUS_CHART_SUCCESS = 'FETCH_PROJECT_STATUS_CHART_SUCCESS';
export const FETCH_PROJECT_STATUS_CHART_FAILURE = 'FETCH_PROJECT_STATUS_CHART_FAILURE';